cdclabs/apps/account1/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from contrib.account.views import *


urlpatterns = patterns('',
    url(r'^signup/$', view=SignupLoginView.as_view(
        featured_form_mixin_class=SignupMultipleFormMixin),
        name='account_signup'),
    url(r'^login/$', view=SignupLoginView.as_view(
        featured_form_mixin_class=LoginMultipleFormMixin),
        name='account_login'),
    url(r'^logout/$', view=LogoutView.as_view(), name='account_logout'),
    url(r'^signup-login/$', view=SignupLoginView.as_view(),
        name='account_signup_login'),
    url(r'^iframes/signup/$', view=SignupLoginIframeView.as_view(
        featured_form_mixin_class=SignupIframeMultipleFormMixin),
        name='account_signup_iframe'),
    url(r'^iframes/login/$', view=SignupLoginIframeView.as_view(
        featured_form_mixin_class=LoginIframeMultipleFormMixin),
        name='account_login_iframe'),
    url(r'^iframes/signup-login/$', view=SignupLoginIframeView.as_view(),
        name='account_signup_login_iframe'),
    url(r'^iframes/signup-login/success/$',
        view=SignupLoginSuccessIframeView.as_view(),
        name='account_signup_login_success_iframe'),
)

cdclabs/apps/forum/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from forum.views import *

urlpatterns = patterns('',
    url(r'^$', index, name='forum_index'),
    url(r'^forum/(?P<forum_slug>\w+)/$', forum, name='forum_forum'),
    url(r'^topic/(?P<topic_id>\d+)/$', topic, name='forum_topic'),
    url(r'^topic/new/(?P<forum_id>\d+)/$', new_post, name='forum_new_topic'),
    url(r'^reply/new/(?P<topic_id>\d+)/$', new_post, name='forum_new_replay'),
    url(r'^post/(?P<post_id>\d+)/$', post, name='forum_post'),
    url(r'^post/(?P<post_id>\d+)/edit/$', edit_post, name='forum_post_edit'),
    url(r'^user/(?P<user_id>\d+)/topics/$', user_topics,
        name='forum_user_topics'),
    url(r'^user/(?P<user_id>\d+)/posts/$', user_posts,
        name='forum_user_posts'),
    url('^markitup_preview/$', markitup_preview, name='markitup_preview'),
)

cdclabs/contrib/avatar/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('contrib.avatar.views',
    url('^change/$', 'change', name='avatar_change'),
)

cdclabs/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.defaults import (
    patterns,
    include,
    url,
)
from django.contrib import admin
from django.views.generic.simple import redirect_to
from feincms.module.page.sitemap import PageSitemap


admin.autodiscover()
sitemaps = {'pages' : PageSitemap}

urlpatterns = patterns('',
    url(r'^favicon\.ico/$', redirect_to, {'url': '/media/favicon.ico'}),
    url(r'^mercury/', include('mercury.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('contrib.account.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^profile/', include('contrib.profile.urls')),
    #url(r'^$', 'feincms.views.base.handler', name='feincms_home'),
    #url(r'^(.*)/$', 'feincms.views.base.handler', name='feincms_handler'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT},
        ),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT},
        ),
    )

urlpatterns += patterns('',
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},
    ),
)

urlpatterns += patterns('',
    url(r'', include('feincms.urls')),
)

cdclabs/apps/forum/models.py
# -*- coding: utf-8 -*-
from base64 import b64encode, b64decode
try:
    import cPickle as pickle
except:
    import pickle
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from forum.settings import *
from forum.managers import TopicManager
from attachment.models import Attachment


__all__ = [
    'Config',
    'ForumCategory',
    'Forum',
    'ForumUserProfile',
    'Post',
    'Topic',
]

class Config(models.Model):
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

class ForumCategory(models.Model):
    """
    Forum Category Model
    """
    name = models.CharField(max_length=100)
    description = models.TextField(default='Category Description')
    ordering = models.PositiveIntegerField(default=1)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ('-ordering', 'created_on')

    def __unicode__(self):
        return self.name

class Forum(models.Model):
    """
    Forum Model
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(default='Forum Desctiption')
    ordering = models.PositiveIntegerField(default=1)
    category = models.ForeignKey(ForumCategory)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    num_topics = models.IntegerField(default=0)
    num_posts = models.IntegerField(default=0)
    last_post = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = _("Forum")
        verbose_name_plural = _("Forums")
        ordering = ('ordering', '-created_on')

    def count_nums_topic(self):
        return self.topic_set.all().count()

    def count_nums_post(self):
        return self.topic_set.all(). \
            aggregate(Sum('num_replies'))['num_replies__sum'] or 0

    def get_last_post(self):
        if not self.last_post:
            return {}
        return pickle.loads(b64decode(self.last_post))

    @models.permalink
    def get_absolute_url(self):
        return ('forum_forum', (), {'forum_slug': self.slug})

    def __unicode__(self):
        return self.name


class Topic(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_('Forum'))
    posted_by = models.ForeignKey(User)
    subject = models.CharField(max_length=999)
    num_views = models.IntegerField(default=0)
    num_replies = models.PositiveSmallIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_reply_on = models.DateTimeField(auto_now_add=True)
    last_post = models.CharField(max_length=255, blank=True)
    closed = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
    objects = TopicManager()

    class Meta:
        ordering = ('-last_reply_on',)
        get_latest_by = ('created_on')
        verbose_name = _("Topic")
        verbose_name_plural = _("Topics")

    def __unicode__(self):
        return self.subject

    def count_nums_replies(self):
        return self.post_set.all().count()

    @models.permalink
    def get_absolute_url(self):
        return ('forum_topic', (), {'topic_id': self.id})

    def get_last_post(self):
        if not self.last_post:
            return {}
        return pickle.loads(b64decode(self.last_post))


class Post(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Topic'))
    posted_by = models.ForeignKey(User)
    poster_ip = models.IPAddressField()
    topic_post = models.BooleanField(default=False)
    message = models.TextField()
    attachments = models.ManyToManyField(Attachment, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null = True)
    edited_by = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-created_on',)
        get_latest_by = ('created_on', )

    def __unicode__(self):
        return self.message[:80]

    def subject(self):
        if self.topic_post:
            return _('Topic: %s') % self.topic.subject
        return _('Re: %s') % self.topic.subject

    def update_attachments(self, attachment_ids):
        self.attachments.clear()
        for attachment_id in attachment_ids:
            try:
                attachment = Attachment.objects.get(pk=attachment_id)
            except:
                continue
            attachment.activated = True
            attachment.save()
            self.attachments.add(attachment)

    @models.permalink
    def get_absolute_url(self):
        return ('forum_post', (), { 'post_id': self.pk })

    def get_absolute_url_ext(self):
        topic = self.topic
        post_idx = topic.post_set.filter(created_on__lte=self.created_on). \
            count()
        page = (post_idx - 1) / CTX_CONFIG['TOPIC_PAGE_SIZE'] + 1
        return '%s?page=%s#p%s' % (topic.get_absolute_url(), page, self.pk)


class ForumUserProfile(models.Model):
    user = models.OneToOneField(User, related_name='forum_profile',
        verbose_name=_('User'))
    last_activity = models.DateTimeField(auto_now_add=True)
    userrank = models.CharField(max_length=30,default="Junior Member")
    last_posttime = models.DateTimeField(auto_now_add=True)
    signature = models.CharField(max_length = 1000, blank = True)

    def __unicode__(self):
        return self.user.username

    def get_total_posts(self):
        return self.user.post_set.count()

    def get_absolute_url(self):
        return self.user.get_absolute_url()

cdclabs/apps/forum/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
#from onlineuser.models import getOnlineInfos
from forum.forms import EditPostForm, NewPostForm
from forum.models import Topic, ForumCategory, Forum, Post


def index(request, template_name="forum/forum_index.html"):
    categories = ForumCategory.objects.select_related(depth=1).all()
    latest_topics = Topic.objects.select_related(depth=1).all()[:10]
    #total_topics = Topic.objects.count()
    #total_posts = Post.objects.count()
    #total_users =  User.objects.count()
    #last_registered_user = User.objects.order_by('-date_joined')[0]
    extend_context = {
        'categories': categories,
        'topics': latest_topics,
        #'total_topics': total_topics,
        #'total_posts': total_posts,
        #'total_users': total_users,
        #'last_registered_user': last_registered_user,
    }
    #extend_context.update(getOnlineInfos(True))
    return render_to_response(template_name, extend_context, RequestContext(request))

def forum(request, forum_slug, template_name="forum/forum_forum.html"):
    forum = get_object_or_404(Forum, slug = forum_slug)
    topics = forum.topic_set.order_by('-sticky', '-last_reply_on').select_related()
    extend_context = {
        'forum': forum,
        'topics': topics,
    }
    return render_to_response(template_name, extend_context, RequestContext(request))

def topic(request, topic_id, template_name="forum/forum_topic.html"):
    topic = get_object_or_404(Topic, id=topic_id)
    topic.num_views += 1
    topic.save()
    objects = list(topic.post_set.order_by('created_on').select_related())
    #qs = Topic.objects.filter(pk=topic_id)
    #obj_dict = dict([(obj.id, obj) for obj in qs])
    #objects = Post.objects.filter(topic__in=qs).select_related()
    #relation_dict = {}
    #for obj in objects:
    #    relation_dict.setdefault(obj.topic_id,[]).append(obj)
    #for id, related in relation_dict.items():
    #    obj_dict[id]._related = related
    extend_context = {
        'topic': topic,
        'posts': objects,
        'replies': objects[1:],
        'thread': objects[0],
    }
    return render_to_response(template_name, extend_context, RequestContext(request))

def post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return HttpResponseRedirect(post.get_absolute_url_ext())

def markitup_preview(request, template_name="forum/markitup_preview.html"):
    return render_to_response(template_name, {'message': request.POST['data']}, RequestContext(request))

@login_required
def new_post(request, forum_id=None, topic_id=None, form_class=NewPostForm, template_name='forum/forum_post.html'):
    qpost = topic = forum = first_post = preview = None
    show_subject_fld = True
    post_type = _(u'topic')
    if forum_id:
        forum = get_object_or_404(Forum, pk=forum_id)
    if topic_id:
        post_type = _(u'reply')
        topic = get_object_or_404(Topic, pk=topic_id)
        forum = topic.forum
        first_post = topic.post_set.order_by('created_on').select_related()[0]
        show_subject_fld = False
    if request.method == "POST":
        form = form_class(request.POST, user=request.user, forum=forum, topic=topic, \
                ip=request.META['REMOTE_ADDR'])
        preview = request.POST.get('preview', '')
        if form.is_valid() and request.POST.get('submit', ''):
            post = form.save()
            if topic:
                return HttpResponseRedirect(post.get_absolute_url_ext())
            else:
                return HttpResponseRedirect(reverse("forum_forum", args=[forum.slug]))
    else:
        initial={}
        qid = request.GET.get('qid', '')
        if qid:
            qpost = get_object_or_404(Post, id=qid)
            initial['message'] = "[quote=%s]%s[/quote]" % (qpost.posted_by.username, qpost.message)
        form = form_class(initial=initial)
    extend_context = {
        'forum':forum,
        'form':form,
        'topic':topic,
        'first_post':first_post,
        'post_type':post_type,
        'preview':preview,
        'show_subject_fld': show_subject_fld,
    }
    extend_context['unpublished_attachments'] = request.user.attachment_set.all().filter(activated=False)
    extend_context['is_new_post'] = True
    return render_to_response(template_name, extend_context, RequestContext(request))

@login_required
def edit_post(request, post_id, form_class=EditPostForm, template_name="forum/forum_post.html"):
    preview = None
    post_type = _('topic')
    edit_post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = form_class(instance=edit_post, user=request.user, data=request.POST)
        preview = request.POST.get('preview', '')
        if form.is_valid() and request.POST.get('submit', ''):
            edit_post = form.save()
            return HttpResponseRedirect('../')
    else:
        form = form_class(instance=edit_post)
    extend_context = {
        'form':form,
        'post': edit_post,
        'topic':edit_post.topic,
        'forum':edit_post.topic.forum,
        'post_type':post_type,
        'preview':preview,
    }
    extend_context['unpublished_attachments'] = request.user.attachment_set.all().filter(activated=False)
    extend_context['show_subject_fld'] = edit_post.topic_post
    return render_to_response(template_name, extend_context, RequestContext(request))

@login_required
def user_topics(request, user_id, template_name='forum/user_topics.html'):
    view_user = User.objects.get(pk=user_id)
    topics = view_user.topic_set.order_by('-created_on').select_related()
    extend_context = {
        'topics': topics,
        'view_user': view_user,
    }
    return render_to_response(template_name, extend_context, RequestContext(request))

@login_required
def user_posts(request, user_id, template_name='forum/user_posts.html'):
    view_user = User.objects.get(pk=user_id)
    posts = view_user.post_set.order_by('-created_on').select_related()
    extend_context = {
        'posts': posts,
        'view_user': view_user,
    }
    return render_to_response(template_name, extend_context, RequestContext(request))

cdclabs/apps/plug/views.py
# -*- coding: utf-8 -*-
from django import settings
from django.views.generic import ListView

class PlugView(ListView):

cdclabs/apps/forum/templates/forum/forum_base.html
{% load i18n %}

{% block title %}{{ FORUM_TITLE }}{{ FORUM_SUB_TITLE }}{% endblock %}

{% block extra_head %}{{ block.super }}{% include "forum/includes/styles.html" %}{% endblock extra_head %}

{% block content %}
<div class="span-16">
{% block latest_topics %}{% endblock latest_topics %}
</div>
<div class="span-8 last">
<div class="block">
  <h3 class="block_title">{% trans "Forum" %}</h3>
  <div class="block_content">{% block forum %}{% endblock forum %}</div>
</div>
</div>
{% endblock %}

cdclabs/apps/forum/templates/forum/forum_forum.html
{% extends "forum/forum_base.html" %}
{% load i18n forum %}

{% block title %}{{ block.super }}{% endblock %}

{% block breadcrumb %}{{ block.super }}{% include "forum/includes/forum_brd_crumbs.html" %}{% endblock breadcrumb %}

{% block content %}
<div class="span-24 last">
  <div class="block">
    <h3 class="block_title">
      <span>{% trans "Forum" %}: {{ forum.name }}</span>
      <span style="float:right">
        {% if user.is_authenticated %}
          <a class="newpost" href="{% url forum_new_topic forum.pk %}"><span>{% trans "Post new topic" %}</span></a>
        {% else %}
          {% trans "You must" %} <a href="{% url auth_login %}">{% trans "Login" %}</a> {% trans "or" %} <a href="{% url registration_register %}">{% trans "register" %}</a> {% trans "to post a topic" %}
        {% endif %}
      </span>
    </h3>
    <div class="block_content">
      <div style="padding:10px;border-bottom: 1px solid #CCC">
		{% load pagination_tags %}
		{% autopaginate topics FORUM_PAGE_SIZE %}
		{% paginate %}
        <h2>
          <span><a title="Permanent link to this forum." rel="bookmark" href="{% url forum_forum forum.slug %}" class="permalink">{{ forum.name }}</a></span>
        </h2>
      </div>
      <div>
        {% include 'forum/includes/topic_list.html' %}
        <div style="padding: 8px 10px 0px 10px;border-top:1px solid #FFF">Page:{% paginate %}</div>
	  </div>
    </div>
  </div>
</div>
{% endblock %}

cdclabs/apps/forum/templates/forum/forum_index.html
{% extends "forum/forum_base.html" %}
{% load i18n forum avatar_tags %}

{% block breadcrumb %}{{ block.super }}<li><span>{% trans "Forum Index" %}</span></li>{% endblock breadcrumb %}

{% block latest_topics %}
<style type="text/css">
.trancate {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    width: 430px;
    height:32px;
    line-height:32px;
}
</style>

<div class="block_plain">
  <div class="cell_head">{% trans "Latest Topic" %}</div>
  {% include "forum/includes/topic_list.html" %}
  <div class="cell_foot">Read More</div>
</div>
{% endblock latest_topics %}

{% block forum %}
<div>
{% for category in categories %}
  <div style="border-bottom:1px solid #CCC;padding:5px 10px">
    <h3>{{ category }}:</h3>
    {% for forum in category.forum_set.all %}
      <span class="forum_name"><a href="{% url forum_forum forum.slug %}">{{ forum.name }}</a></span> |
    {% endfor %}
  </div>
{% endfor %}
</div>
{% endblock forum %}



{% block forums %}
<!-- forum-wrap begins -->
<div id="forum_wrap" class="forum">

<!-- forum-index begins -->
<div id="forum_index" class="forum-page basic_page">
  <div class="hr"><hr /></div>
  <!-- forum-main begins -->
  <div id="forum_main">
    <div class="main_head">
      <h1 class="hn"><span>{{ FORUM_TITLE }}</span></h1>
    </div>
    {% for category in categories %}
    <div class="main_subhead">
      <h2 class="hn"><span>{{ category }}</span></h2>
      <p class="item_summary">
        <span>
          <strong class="info_topics">{% trans "topics" %}</strong>,
          <strong class="info_posts">{% trans "posts" %}</strong>,
          <strong class="info_lastpost">{% trans "last post" %}</strong>
        </span>
      </p>
    </div>
    <div class="main_content main_category">
    {% for forum in category.forum_set.all %}
    <!-- forum begins -->
      <div id="forum" class="main-item {% cycle 'odd' 'even' %} {% if forloop.first %}main_item1{% endif %}">
        <span class="icon "><!-- --></span>
        <div class="item_subject">
          <h3 class="hn"><a href="{% url forum_forum forum.slug %}"><span>{{ forum }}</span></a></h3>
          <p>{{ forum.description }}</p>
        </div>
        <ul class="item_info">
          <li class="info_topics">
            <strong>{{ forum.num_topics }} </strong> <span class="label">{% trans "topics" %}</span>
          </li>
          <li class="info_posts">
            <strong>{{ forum.num_posts }} </strong> <span class="label">{% trans "posts" %}</span>
          </li>
          <li class="info_lastpost">
            <span class="label">{% trans "Last post" %}:</span>
            <strong>{{ forum.get_last_post.update|timesince }}</strong>
            <cite>by {{ forum.get_last_post.posted_by }}</cite>
          </li>
        </ul>
      </div>
    <!-- forum ends -->
    {% endfor %}
    </div>
  <!-- forum-#id ends -->
  {% endfor %}
  </div>
  <!-- forum-main ends -->

  <!-- forum_qpost -->

  <!-- forum-stats begins -->
  <div id="forum_stats" class="gen_content">
    <h2 class="hn"><span>Forum statistics</span></h2>
    <ul>
      <li class="st_users">
        <span>{% trans "Total number of registered users" %}: <strong>{{ total_users }} </strong></span>
      </li>
      <li class="st_users">
        <span>{% trans "Newest registered user" %}:
          <strong><a href="{% url profile_detail last_registered_user.username %}">{{ last_registered_user.username }}</a></strong>
        </span>
      </li>
      <li class="st_activity">
        <span>{% trans "Total number of topics" %}: <strong>{{ total_topics }}</strong></span>
      </li>
      <li class="st_activity">
        <span>{% trans "Total number of posts" %}: <strong> {{ total_posts }} </strong></span>
      </li>
    </ul>
  </div>
  <!-- forum-stats ends -->

  <div class="gen_content" id="forum_online">
    <h3 class="hn">
      <span>
        {% trans "Currently online" %} <strong> {{ total_onlines }} </strong> ( <strong> {{ total_onlines_guest }} </strong> {% trans "guests" %}, <strong>{{ total_onlines_user }}</strong> {% trans "registered user" %} )
      </span>
    </h3>
  </div>
  </div>
  <!-- forum-index ends -->
</div>
<!-- forum-wrap ends -->

{% endblock forums %}

cdclabs/apps/forum/templates/forum/markitup_preview.html
{% load i18n %}
{% load lbforum %}
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% block html_declare %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
{% endblock %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% trans "preview" %}</title>
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}scripts/markitup/templates/preview.css" />
</head>
<body>
{{ message|bbcode|safe }}
</body>
</html>

cdclabs/apps/forum/templates/forum/post_paginate.html
{% load i18n %}
{% if pages %}
<span class="item-nav">
	( 
	<span>{% trans "Pages" %}&nbsp;</span>
	{% for p in pages %}
	<a href="{% url forum_topic topic.id %}?page={{p}}">{{p}}</a>
	{% endfor %}
	{% if page_count > window %}
	...
	<a href="{% url forum_topic topic.id %}?page={{page_count}}">{{page_count}}</a>
	{% endif %}
	)
</span>
{% endif %}

cdclabs/apps/forum/templates/forum/redirect.html
{% extends "lbforum/base.html" %}

{% load i18n %}

{% block extra_header %}
<meta http-equiv="refresh" content="5;URL={% block redirect_url %}{{ redirect_url }}{% endblock %}" />
{% endblock %}

{% block content %} 
<div id="brd-wrap" class="brd-page">
	<div id="brd-redirect" class="brd">
		<div id="brd-main" class="main basic">
			<div class="main-head">
				<h1 class="hn"><span>{% block main_head %}{% endblock %}</span></h1>
			</div>
			<div class="main-content main-message">
				<p>{% trans "You should automatically be forwarded to a new page in 5 second." %}
					<span>
						<a href="{% block redirect_url_ %}{{ redirect_url }}{% endblock %}">
							{% trans "Click here if you do not want to wait any longer (or if your browser does not automatically forward you)" %}
						</a>
					</span>
				</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

cdclabs/apps/forum/templates/forum/user_topics.html
{% extends "forum/forum_base.html" %}
{% load i18n forum %}


{% block title %}{{  block.super }}{% endblock %}

{% block content %}
<div id="actionbox"></div>  

    <div id="brd-wrap" class="brd">
        <div id="brd-searchtopics" class="brd-page paged-page">
            {% include 'forum/includes/header.html' %}
            {% include 'forum/includes/announce.html' %}

            <div class="hr"><hr /></div>

            <div class="crumbs gen-content" id="brd-crumbs-top">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url forum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span>&raquo;</span>
						{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                    </span> 
                </p>
            </div>

            <div id="brd-main">
                <div class="main-pagepost gen-content" id="brd-pagepost-top">
                    {% load pagination_tags %}
                    {% autopaginate topics 50 %}
                    {% paginate %}
                    <p class="posting">
                    </p>
                </div>
                <div class="main-head">
                    <h1 class="hn">
                        <span>
							{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                            <small></small>
                        </span>
                    </h1>
                </div>

                {% include 'forum/includes/topic_list.html' %}

                <div class="main-options gen-content">
                    <p class="options"></p>
                </div>

                <div class="main-pagepost gen-content" id="brd-pagepost-end">
                    {% paginate %}	
                    <p class="posting">
                    </p>
                </div>

            </div>

            <div class="crumbs gen-content" id="brd-crumbs-end">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url forum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span>&raquo;</span>
						{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                    </span> 
                </p>
            </div>

            <div class="hr"><hr /></div>

            {% include 'forum/includes/copyright.html' %}

        </div>
    </div>
{% endblock %}